name: production | deploy

on:
  push:
    branches:
      - production

jobs:
  assets:
    runs-on: ubuntu-latest
    name: production | deploy
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Deploy to production
        env:
          FORGE_PRODUCTION_DEPLOYMENT: ${{ secrets.FORGE_PRODUCTION_DEPLOYMENT }}
        run: curl "$FORGE_PRODUCTION_DEPLOYMENT"?sha=${{ github.sha }}
